---
# Main playbook to setup complete Kubernetes cluster
- name: Setup Kubernetes Cluster
  hosts: all
  gather_facts: yes
  
- import_playbook: common.yml
- import_playbook: control-plane.yml
- import_playbook: worker-nodes.yml
